# https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#env

name: Validate production PR source

on:
  pull_request:
    branches:
      - production

jobs:
  source-branch:
    name: Require "development" source branch for PRs to "production"
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: ${{ github.head_ref }}
      HEAD_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
      BASE_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Validate source branch
        shell: bash
        run: |
          if [ "$SOURCE_BRANCH" != "development" ] || [ "$HEAD_REPOSITORY" != "$BASE_REPOSITORY" ]; then
            echo "PRs to "production" must come from "development" branch."
            exit 1
          fi
